export { SendCore } from './client';
export { SendCoreError, isSendCoreError } from './errors';
export { EmailBuilder } from './client';
export type {
  SendCoreConfig,
  SendEmailParams,
  SendEmailResponse,
  EmailAttachment,
  SubscribeParams,
  UnsubscribeParams,
  AddDomainParams,
  Domain,
  DnsRecord,
  VerifyEmailParams,
  BatchVerifyParams,
  VerificationResult,
  AnalyticsParams,
  AnalyticsData,
  WebhookPayload,
  EmailBuilderParams,
  SendCoreErrorDetail,
  Workflow,
  WorkflowStep,
  WorkflowExecution,
  WorkflowExecutionLog,
  CreateWorkflowParams,
  Broadcast,
  CreateBroadcastParams,
  ScheduleBroadcastParams,
  AudienceList,
  CreateAudienceListParams,
  AddContactParams,
  EmailTemplate,
  CreateTemplateParams,
  Suppression,
  AddSuppressionParams,
  SuppressionListParams,
  ApiKey,
  CreateApiKeyParams,
  CreateApiKeyResponse,
  AgentInbox,
  CreateAgentInboxParams,
  InboundEmail,
  SendAsAgentParams,
  PaginatedEmails,
} from './types';
